//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOATest.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEntidad", Namespace="http://schemas.datacontract.org/2004/07/ServicioSOA")]
    [System.SerializableAttribute()]
    public partial class ClienteEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Cliente {
            get {
                return this.Ape_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_ClienteField, value) != true)) {
                    this.Ape_ClienteField = value;
                    this.RaisePropertyChanged("Ape_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_Cliente {
            get {
                return this.Cod_ClienteField;
            }
            set {
                if ((this.Cod_ClienteField.Equals(value) != true)) {
                    this.Cod_ClienteField = value;
                    this.RaisePropertyChanged("Cod_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_Cliente {
            get {
                return this.Dir_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_ClienteField, value) != true)) {
                    this.Dir_ClienteField = value;
                    this.RaisePropertyChanged("Dir_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Cliente {
            get {
                return this.Nom_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ClienteField, value) != true)) {
                    this.Nom_ClienteField = value;
                    this.RaisePropertyChanged("Nom_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Cliente {
            get {
                return this.Tel_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_ClienteField, value) != true)) {
                    this.Tel_ClienteField = value;
                    this.RaisePropertyChanged("Tel_Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DoWork", ReplyAction="http://tempuri.org/IClienteService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DoWork", ReplyAction="http://tempuri.org/IClienteService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Registrar", ReplyAction="http://tempuri.org/IClienteService/RegistrarResponse")]
        bool Registrar(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Registrar", ReplyAction="http://tempuri.org/IClienteService/RegistrarResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAsync(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Modificar", ReplyAction="http://tempuri.org/IClienteService/ModificarResponse")]
        bool Modificar(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Modificar", ReplyAction="http://tempuri.org/IClienteService/ModificarResponse")]
        System.Threading.Tasks.Task<bool> ModificarAsync(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Eliminar", ReplyAction="http://tempuri.org/IClienteService/EliminarResponse")]
        bool Eliminar(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Eliminar", ReplyAction="http://tempuri.org/IClienteService/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Buscar", ReplyAction="http://tempuri.org/IClienteService/BuscarResponse")]
        SOATest.ProxyCliente.ClienteEntidad[] Buscar(SOATest.ProxyCliente.ClienteEntidad entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Buscar", ReplyAction="http://tempuri.org/IClienteService/BuscarResponse")]
        System.Threading.Tasks.Task<SOATest.ProxyCliente.ClienteEntidad[]> BuscarAsync(SOATest.ProxyCliente.ClienteEntidad entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : SOATest.ProxyCliente.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<SOATest.ProxyCliente.IClienteService>, SOATest.ProxyCliente.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool Registrar(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.Registrar(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsync(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.RegistrarAsync(entidad);
        }
        
        public bool Modificar(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.Modificar(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAsync(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.ModificarAsync(entidad);
        }
        
        public bool Eliminar(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.Eliminar(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.EliminarAsync(entidad);
        }
        
        public SOATest.ProxyCliente.ClienteEntidad[] Buscar(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.Buscar(entidad);
        }
        
        public System.Threading.Tasks.Task<SOATest.ProxyCliente.ClienteEntidad[]> BuscarAsync(SOATest.ProxyCliente.ClienteEntidad entidad) {
            return base.Channel.BuscarAsync(entidad);
        }
    }
}
